[build]
build-std = true                              # do not build the std library. has precedence over xargo
xargo = true                                  # enable the use of xargo by default
zig = true                                    # do not use zig cc for the builds
default-target = "x86_64-unknown-linux-gnu"   # use this target if none is explicitly provided
